[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
internal_port = 8080
port = 8080 